apiVersion: argoproj.io/v1alpha1
kind: Rollout
meta
  name: demo-app
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: demo-app
      previewService: demo-app-preview  # опционально
      autoPromotionEnabled: true        # сразу переключать (для демо)
  selector:
    matchLabels:
      app: demo-app
  template:
    meta
      labels:
        app: demo-app
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
meta
  name: demo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-app
---
# Опционально: preview-сервис для ручной проверки
apiVersion: v1
kind: Service
meta
  name: demo-app-preview
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-app
    rollouts-pod-template-hash: <hash>  # Argo Rollouts подставит автоматически
