apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: demo-app
      previewService: demo-app-preview
      autoPromotionEnabled: false  # РУЧНОЕ переключение
      previewReplicaCount: 1       # 1 под для preview
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-app
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-preview
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-app
